{% set name = "libdiffpy" %}
{% set version = "1.4.1rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/diffpy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e4338b00d5ed77cafeb487a1a9071344a5fb46d034825bba697efbc6fdde05bd

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - scons
  host:
    - libboost-devel
    - gsl
    - libobjcryst ==2024.1.1
    - dlfcn-win32  # [win]
  run:
    - gsl

test:
  commands:
    - test -f $PREFIX/lib/libdiffpy${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\diffpy.lib exit 1  # [win]

about:
  home: https://github.com/diffpy/libdiffpy
  summary: "C++ calculators of PDF, bond valence sum and other pair quantities."
  license: BSD-3-Clause
  license_file: LICENSE.txt
  doc_url: https://www.diffpy.org/libdiffpy/
  dev_url: https://github.com/diffpy/libdiffpy

extra:
  recipe-maintainers:
    - pavoljuhas
    - sbillinge
    - st3107
    - Tieqiong
