{% set name = "libdiffpy" %}
{% set version = "1.4.0" %}
{% set sha256 = "0b08e161e8f2ed517ace9223c0315258c492c626d84dd06ff23ad9293c16e161" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or not py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - boost
    - gsl
    - libobjcryst >=2017.1.1,2017.1.*
    - scons
  run:
    - boost
    - gsl
    - libobjcryst >=2017.1.1,2017.1.*

test:
  commands:
    - test -f $PREFIX/lib/libdiffpy${SHLIB_EXT}

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD
  license_file: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
    - pavoljuhas
