appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IwknkHFquJ9mLqmkxpB8W+/nJCIlRYqTcTvDIH0f8hvnQwQOOAG2nW6hT41Lxi0vykoWTPpHA7OJ5hPbXGKYy/eCM/LZzyBZbpuvj7S0aGdNWYnr7dm+vGjRwGqdbHJp3kZtLw/d7RPqfEj15bOFlCzZndD4EvdYSnh7C1XehMPqIW9leRgs1fzHrFQNOpi/EAIsRHVklkfncha8urDVDiysq0Q4fMmtYOmN9pL4p1v8ceagxb144whkQqG6A1cYkLXEzDIMvsaASTSpJ+B9GVWtppQEErQXBuf/36gm2palS+oqrajO49N/0JI+XHUZ30Z0U4btlWklIAGcf4BynO1QhlB4ROHVXlI/VBA/oEPaMq1krr+PAt/JBbwL55esM5r8EwZqPRxzBGZhWfy3TqIL0JHu6PsyGIEs7O80kZ1nYH+kdvbD5NEdZG/uRb4gktiNhUwU7AqAYxUdluzA0Uj43YBDWjQ5HoXxDEndU3v3qc46APUqOH4aMZBRuTyig+vTYZXiBpaFaVh1cRdsRe6LCyKdGfe8pBGZeOzQJqG4iV6NY1Gm+r/KDx9cr4x7aU1pBZGK61s54jNDaiO8CAla7bq3ks0UH/voOpFHx9Yn7sf3RHhSh8G7BNjcm3Z2y8358sTiix2hJacxgA50ruRBxbaG/ITRd4qhiWpLgn8=}
conda_forge_output_validation: true
