travis:
  secure:
    BINSTAR_TOKEN: DC4cW0JffyzSAqwxM4IHNLz1Io1rRElyXPPIDvhGvn0skCoi0yQ9w4s4w04VF2U5VDXbAPdTOqYtB/Z2DOzC+lxRWdnrlOXII0RwyRmX0lKNHhwsMZUXdXXMgdNKHnIQbE1dny01V6kP0cqKZYO25umM44acj2e2ln26+if4shH10WY2saaFapI2cNJ5kMRiSvHtAksehMpjuxtY11FygjQCPHRux/CPGd4N0isyZyi1oMBCU8tcIeemLf5GztXQ8BCjVVNfTPwxQfF2jvE9IEkXdtfeQm+1P0av7+H5/jY+fsaNsdyDjggCyLrROQaM8dU//fhXqryAjFu27K4TVdpPFzGzXTRAc6oeTHFnjTR6VxikhWDeKme92IlwjVUaiN8mF/3jaSDIesepZycpkBq/Tqttuh2ktsghqMZQqjPjgLp7iI23nesmBOB7SkGUnG3Ut2QqOlmCIh8Bk40ycKz5HEEisum4Ki4+NVlZjkABZH8R4sGRDOd9RaQgQEQ16Vr3hV1jKwNFid4JL2o0Q5heh66bXVF55dbHum1Hp2siDpMVSoQfgxRg7pdiTB7gOwiS18IOYE0hbLt/dr17hj562jB2imce1jkvemeohqiOIDuMqQ/8sndwC1jGXCJhXt3+22yOREaMgaFR+mXKMIvY5B8JClZgpqdjfmpHevY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
